name: Publish bundle to charm store

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Publish bundle
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        set -eux
        sudo snap install charm --classic
        sudo snap install juju-helpers --classic --channel edge
        sudo pip3 install charmcraft==1.0.0

    - name: Publish bundle
      env:
        CHARMSTORE_CREDENTIAL: ${{ secrets.CHARMSTORE_CREDENTIAL }}
      run: |
        set -eux
        echo $CHARMSTORE_CREDENTIAL > ~/.go-cookies
        juju-bundle publish \
            --url cs:~argo-charmers/argo \
            --publish-charms \
            --publish-namespace argo-charmers
