name: MicroK8s Test

on:
  - push
  - pull_request

jobs:
  build:
    name: Deploy to microk8s
    runs-on: ubuntu-latest

    steps:
    - name: Check out repo
      uses: actions/checkout@v2

    - uses: balchua/microk8s-actions@v0.2.2
      with:
        channel: 'latest/stable'
        addons: '["dns", "storage", "rbac", "metallb:10.64.140.43-10.64.140.49"]'

    - name: Install dependencies
      run: |
        set -eux
        sudo snap install charm --classic
        sudo pip3 install charmcraft==1.0.0
        sudo snap install juju --classic
        sudo snap install juju-helpers --classic
        sudo snap install juju-wait --classic

    - name: Set up Argo
      run: |
        set -eux
        sg microk8s -c 'juju bootstrap microk8s uk8s'
        juju add-model argo microk8s --config update-status-hook-interval=10s
        juju bundle deploy --build
        sleep 10
        juju wait -wvt 300
    - name: Get pod statuses
      run: kubectl get all -A
      if: failure()

    - name: Describe deployments
      run: kubectl describe deployments -A
      if: failure()

    - name: Describe replicasets
      run: kubectl describe replicasets -A
      if: failure()

    - name: Get argo-controller logs
      run: kubectl logs -n argo --tail 1000 -ljuju-app=argo-controller
      if: failure()

    - name: Get argo-controller operator logs
      run: kubectl logs -n argo --tail 1000 -ljuju-operator=argo-controller
      if: failure()

    - name: Get argo-ui logs
      run: kubectl logs -n argo --tail 1000 -ljuju-app=argo-ui
      if: failure()

    - name: Get argo-ui operator logs
      run: kubectl logs -n argo --tail 1000 -ljuju-operator=argo-ui
      if: failure()
