name: Unit Tests 

on:
  - push
  - pull_request

jobs:
  unit:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - run: |
          sudo apt update
          sudo apt install tox
      - run: tox -vve unit

  lint:
    name: Run Lint Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - run: |
          sudo apt update
          sudo apt install tox
      - run: tox -vve lint
